### ISSUE TITLE
exclude-files is not a valid input

### ISSUE THREAD

**Issue by obenland** [WordPress/plugin-check-action#180]
I'm not sure why, but I get the following warning when executing the action with `exclude-files` defined and they don't get passed as a CLI arg:

```
Warning: Unexpected input(s) 'exclude-files', valid inputs are ['repo-token', 'build-dir', 'checks', 'exclude-checks', 'categories', 'exclude-directories', 'ignore-warnings', 'ignore-errors', 'include-experimental', 'wp-version']
```

Example run: https://github.com/obenland/wp-approve-user/actions/runs/11207052884/job/31148867122
Workflow. file: https://github.com/obenland/wp-approve-user/pull/36/files

**Comment by swissspidy** [comment]
Grüezi 👋 

`exclude-files` is a brand new addition in #169 and isn't part of a tagged release just yet. Something I'll try to do asap though, together with any other missing updates.

Interesting idea to use this for `.distignore`. It will probably fail for more complex usage like when using exclamation marks and risks being imprecise or even incorrect if your deployment process ever changes.

You might want to instead use a proper build step prior to using Plugin Check. Something like this:

```yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
            php-version: latest
            coverage: none
            tools: wp-cli

      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command:@stable

      - name: Build plugin
        run: |
          wp dist-archive . ./wp-approve-user.zip
          mkdir tmp-build
          unzip wp-approve-user.zip -d tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1.0.6
        with:
          build-dir: './tmp-build/wp-approve-user'
```

**Comment by swissspidy** [comment]
Note to self: mention `.distignore` use case as an example in the readme.

**Comment by 2ndkauboy** [comment]
I ran into similar issues today. I disliked the idea of using a static plugin name. Given the project name is the plugin name, I came up with this general action (which also installs composer and npm dependencies and build assets using wp-scripts:):

```yaml
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Composer install
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6
          coverage: none
          tools: wp-cli
      - run: composer install --no-dev --ignore-platform-reqs --optimize-autoloader

      - name: Assets build
        run: |
          npm install
          npm run build

      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command:@stable

      - name: Build plugin
        run: |
          wp dist-archive . ./${{ github.event.repository.name }}.zip
          mkdir tmp-build
          unzip ${{ github.event.repository.name }}.zip -d tmp-build

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: ./tmp-build/${{ github.event.repository.name }}

```
