### ISSUE TITLE
Allow setting textdomain manually

### ISSUE THREAD

**Issue by JUVOJustin** [WordPress/plugin-check-action#184]
First off thank you very much for the github action. I already implemented it in our plugin boilerplate CI: https://github.com/JUVOJustin/wordpress-plugin-boilerplate

However when the workflow clones the repo with a simple 
`- uses: actions/checkout@v4`

And the repository has a different name than the textdomain configured in the plugin header, the pipeline seems to use the folders name inside the github action which is the repo name by default.

**Example:**
Repo: my-awesome-plugin
Textdomain: awesome-plugin

**Result:**
Mismatched text domain. Expected 'my-awesome-plugin' but got 'awesome-plugin'.

By passing the expected textdomain to the action this could be solved.

**Comment by swissspidy** [comment]
You could also just do

```
- name: Checkout repository with correct slug
  uses: actions/checkout@v4
  with:
    path: 'awesome-plugin'
```

No need to reimplement this in this action :)

**Comment by jcvignoli** [comment]
@swissspidy  I have a similar issue and your trick doesn't work. My plugin is availabe on "/dist", and it's name is "my-plugin".

with the following config:

```
name: 'WP plugin check'
on:
  push:
    branches: "*"
  pull_request:
jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: 'my-plugin'
            
    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        build-dir: './dist'
        exclude-directories: 'vendor,.wordpress-org'

```

I get the following github error:

`ℹ Starting 'wp plugin list-check-categories' on the cli container. 
name	slug
General	general
Plugin Repo	plugin_repo
Security	security
Performance	performance
Accessibility	accessibility
✔ Ran `wp plugin list-check-categories` in 'cli'. (in 0s 484ms)
ℹ Starting 'wp plugin get dist --field=requires_plugins' on the cli container. 
Error: The 'dist' plugin could not be found.
✖ Command failed with exit code 1
Command failed with exit code 1
Error: Process completed with exit code 1.`

What should I do?

**Comment by jcvignoli** [comment]
I found a [similar issue with the WP plugin](https://github.com/WordPress/plugin-check/issues/774), which could be resolved with `--slug=my-plugin` apparently.

**Comment by swissspidy** [comment]
Setting `path: 'my-plugin'` of course does not work if your actual built plugin file is in a differently named subfolder and you pass that one to Plugin Check.

I will consider adding for `--slug`, but I worry that it will lead to issues with accidentally hiding legit issues. So it will need to be documented well.

In the meantime Irecommend just renaming your folder.

```yaml
  - name: Build plugin
    run: |
      mv ./dist ${{ runner.temp }}/my-plugin

  - name: Run plugin check
    uses: wordpress/plugin-check-action@v1.0.6
    with:
      build-dir: ${{ runner.temp }}/my-plugin
```
