### ISSUE TITLE
Intermittent database connection issues in wp-env

### ISSUE THREAD

**Issue by slaFFik** [WordPress/plugin-check-action#257]
Related to #119 

When the action sets up the environment, it uses MySQL and the wordpress/env, I suppose.

I periodically get the "mysql is not running" error. Re-running the action fixes that, but this should be done manually, which is annoying.

```
✖ Error while running docker compose command.
 Container 9e45[64](https://github.com/some-org/some-repo/actions/runs/13225441537/job/36915733649#step:6:69)a086e529c79f175e263b1d1222-tests-mysql-1  Running
 Container 9e4564a086e529c79f175e263b1d1222-tests-wordpress-1  Running
Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or that contact with the database server at `tests-mysql` could not be established. This could mean your host’s database server is down.
```

Using SQLite would be a more stable solution, I think. 

We do not run the plugin per se, so whether the plugin won't be able to work on SQLite correctly is irrelevant as the action checks the plugin code, and not the plugin functionality.

<details><summary>GH Workflow File</summary>
<p>

```yml
name: 'plugin-check'
on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: wp-cli
          
      - name: Install latest version of dist-archive-command
        run: wp package install wp-cli/dist-archive-command

      - name: Build plugin
        run: |
          composer run build
          cd ./build
          unzip *.zip -d .
          mv plugin-slug-internal plugin-slug

      - name: Run Plugin Check
        uses: wordpress/plugin-check-action@v1
        with:
          wp-version: "latest"
          build-dir: './build/plugin-slug'
          exclude-directories: 'vendor'
          categories: |
            performance
            plugin_repo
            security
          include-experimental: false
```

</p>
</details>

**Comment by swissspidy** [comment]
> We do not run the plugin per se, so whether the plugin won't be able to work on SQLite correctly is irrelevant as the action checks the plugin code, and not the plugin functionality.

Actually, the Plugin Check runtime checks do activate and run your plugin.

So not only would PCP need to work with SQLite, but your plugin would need to as well.

I don‘t see us trying to shove SQLite support into a wp-env setup. It wouldn‘t solve these intermittent issues.

So if you want SQLite support, then I‘d close this as a duplicate of #119.

However, let‘s take a step back. Your issue is not the absence of SQLite. It‘s the intermittent mysql connection in wp-env. This is best reported at the Gutenberg repository.

In this action, we could add some automatic retry mechanism in the meantime.

**Comment by slaFFik** [comment]
That's correct.
The main problem is a flaky mysql.

Technically, the retry mechanism can be done like this:
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-attempts: 3
      delay: 30s
```

That's inside my own yml file. But I think it will retry even after successful PCP check (with found errors/warnings), which isn't helpful.

So yes, adding an automatic retry in the action when the error message contains "Error establishing a database connection" would definitely be helpful.
